---
  - name: update
    apt:
      upgrade=dist
      autoremove=yes
      update_cache=yes

  - name: install packages
    apt:
      name={{ item }}
      state=present
      autoremove=yes
    with_items:
      - putty-tools
      - dos2unix
      - wmctrl
      - byzanz
      - alien
      - tree
      - jq
      - xmlstarlet
      - multitail
      - ngrep
      - nmap
      - sslscan
      - dnsutils
      - xdg-utils
      - unzip
      - bash-completion
      - ffmpeg
