---
  - name: add git-core ppa
    apt_repository:
      repo='ppa:git-core/ppa'

  - name: update
    apt:
      upgrade=dist
      autoremove=yes
      update_cache=yes

  - name: install git
    apt:
      name={{ item }}
      state=present
      autoremove=yes
    with_items:
      - gitk
      - git-gui

  - name: output git version
    command: git --version
